version: '3'

services:
   psecubuntu:
      stdin_open: true # -i
      tty: true # -t
      image: psecubuntu
      command: "iptables -P INPUT ACCEPT"
      networks:
         static-network:
            ipv4_address: 172.20.128.2 
   portknock:
      stdin_open: true # -i
      tty: true # -t
      image: portknock
      cap_add:
         - NET_ADMIN
      networks:
         static-network:
            ipv4_address: 172.20.110.7 

networks:
   static-network:
      driver: bridge
      ipam:
         driver: default         
         config:
            - subnet: 172.20.0.0/16
      driver_opts:
         com.docker.network.bridge.name: psec_lab_net

  #    securityContext:
  #       privileged: true
  #       capabilities:
  #          add: ["NET_ADMIN"]
